version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build: ./llm
    ports:
      - "3000:3000"
    volumes:
      - ./llm:/app
    depends_on:
      - backend  # Frontend depends on backend, but backend does not depend on frontend

